apiVersion: v1
kind: Secret
metadata:
  name: guestbook-db-credentials
type: Opaque
data:
  POSTGRES_USER: <base64-encoded-username> # Replace with your desired username
  POSTGRES_PASSWORD: <base64-encoded-password> # Replace with your desired password
  POSTGRES_DB: <base64-encoded-database-name> # Replace with your desired database name
