YAML
apiVersion: v1
kind: PersistentVolume
metadata:
  name: guestbook-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/guestbook-db
  storageClassName: standard
